import type { Metadata } from "next";
import { Inter, Libre_Barcode_39_Text } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const barcode39 = Libre_Barcode_39_Text({
  weight: "400",
  subsets: ["latin"],
  // this will be the css variable
  variable: "--font-barcode-39",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <style jsx global>
        {`
          :root {
            --font-barcode-39: ${barcode39.style.fontFamily};
          }
        `}
      </style>
    </html>
  );
}
